// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Data;

#nullable disable

namespace webapi.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("webapi.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Post number 1",
                            Title = "This post number 1 and this is good"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Post number 2",
                            Title = "This post number 2 and this is good"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Post number 3",
                            Title = "This post number 3 and this is good"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "Post number 4",
                            Title = "This post number 4 and this is good"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Post number 5",
                            Title = "This post number 5 and this is good"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "Post number 6",
                            Title = "This post number 6 and this is good"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
